import { CSSProperties } from "react";

export const STYLE = {
  bg: "#FFFFFF",
  bgAlt: "#FFF8F5",
  bgEdge: "#FFEFE8",
  card: "#FFFFFF",
  cardDark: "#1E1E2E",
  accent: "#D97757",
  accentLight: "#F0A47A",
  accentDark: "#B85C3E",
  teal: "#2CBAA0",
  textDark: "#2A1F1A",
  textMuted: "#6A5A4A",
  textLight: "#FFFFFF",
  shadow: "0 12px 40px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.03)",
  shadowHeavy: "0 20px 60px rgba(0,0,0,0.1), 0 8px 24px rgba(0,0,0,0.05)",
  fontHeading: "'Rubik', sans-serif",
  fontBody: "'Heebo', sans-serif",
  fontMono: "'JetBrains Mono', 'Fira Code', monospace",
  cardRadius: 28,
  cardPadding: 48,
  terminal: "#1E1E2E",
  terminalText: "#CDD6F4",
  terminalGreen: "#A6E3A1",
  terminalYellow: "#F9E2AF",
  terminalBlue: "#89B4FA",
  terminalPink: "#F5C2E7",
  terminalRed: "#F38BA8",
};

export const bgStyle: CSSProperties = {
  background: `radial-gradient(ellipse at 0% 0%, ${STYLE.bgEdge} 0%, transparent 40%),
               radial-gradient(ellipse at 100% 100%, ${STYLE.bgEdge} 0%, transparent 40%),
               linear-gradient(180deg, ${STYLE.bg} 0%, ${STYLE.bgAlt} 100%)`,
  width: "100%",
  height: "100%",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  fontFamily: STYLE.fontBody,
  direction: "rtl",
  overflow: "hidden",
};
